import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { readFileSync } from 'node:fs'
import {
  configurationResetNeedsConfirmation, configurationText, configurationWithRawMember, createSchemaValue, getSchemaView, parseJsonSafely,
  SchemaNumberSession, schemaPointer, setConfigurationProperty, validateConfiguration,
} from './json-schema.ts'

const draft4 = 'http://json-schema.org/draft-04/schema#'
const serverSchemas = JSON.parse(readFileSync(new URL('../../../../tests/Nexus.Tests/API/v1/fixtures/source-configuration-schemas.json', import.meta.url), 'utf8')) as Record<string, unknown>

describe('server-generated configuration contracts', () => {
  it('accepts generated CLR formats without changing local times or decimal values', () => {
    const schema = serverSchemas['formats']
    const value = { id: '04cbf330-2337-4361-90db-3798a4b654cb', count: 12, amount: 0.3,
      time: '12:34:56.1234567', timestamp: '2026-09-16T12:34:56.1234567' }
    const before = JSON.stringify(value)
    assert.equal(validateConfiguration(schema, {}).valid, true)
    assert.equal(validateConfiguration(schema, value).valid, true)
    assert.equal(JSON.stringify(value), before)
    assert.equal(validateConfiguration(schema, { ...value, count: -1 }).valid, false)
    assert.equal(validateConfiguration(schema, { ...value, id: 'invalid' }).valid, false)
    assert.equal(validateConfiguration(schema, { ...value, time: '25:34:56' }).valid, false)
  })

  it('accepts combined flags and enforces generated byte bounds including nullable roots', () => {
    const schema = serverSchemas['flagsAndByte']
    assert.equal(validateConfiguration(schema, { flags: 3, nullableFlags: null, value: 255, nullableValue: null }).valid, true)
    for (const value of [-1, 256, 1.5]) {
      assert.equal(validateConfiguration(schema, { value }).valid, false)
      assert.equal(validateConfiguration(schema, { flags: value }).valid, false)
    }
    const root = serverSchemas['nullableFlagsRoot']
    assert.equal(validateConfiguration(root, null).valid, true)
    assert.equal(validateConfiguration(root, 3).valid, true)
    assert.equal(validateConfiguration(root, 256).valid, false)
    assert.equal(getSchemaView(root).kind, 'integer')
    assert.equal(getSchemaView(root).nullable, true)
  })

  it('preserves required presence and nullable roots from the actual descriptions generator', () => {
    const schema = serverSchemas['nonNullableRoot']
    assert.equal(validateConfiguration(schema, null).valid, false)
    assert.equal(validateConfiguration(schema, {}).valid, false)
    assert.equal(validateConfiguration(schema, { requiredNullable: null }).valid, true)
    assert.equal(validateConfiguration(schema, { requiredNullable: null, optionalNonNullable: null }).valid, false)
    const nullable = serverSchemas['nullableRoot']
    assert.equal(validateConfiguration(nullable, null).valid, true)
    assert.equal(validateConfiguration(nullable, {}).valid, false)
    assert.equal(validateConfiguration(nullable, { requiredNullable: 'value' }).valid, true)
    assert.equal(getSchemaView(nullable).nullable, true)
    assert.equal(getSchemaView(nullable).kind, 'object')
  })

  it('renders and validates generated reference, dictionary, and nullable value roots', () => {
    const reference = serverSchemas['nullableReference']
    assert.equal(validateConfiguration(reference, { child: null }).valid, true)
    assert.equal(validateConfiguration(reference, { child: {} }).valid, false)
    assert.equal(validateConfiguration(reference, { child: { name: 'child' } }).valid, true)
    assert.equal(getSchemaView(reference, ['#/properties/child']).nullable, true)
    const dictionary = serverSchemas['dictionaryRoot']
    assert.equal(validateConfiguration(dictionary, { first: { name: 'child' } }).valid, true)
    assert.equal(validateConfiguration(dictionary, { first: null }).valid, false)
    assert.equal(getSchemaView(dictionary).allowAdditional, true)
    const value = serverSchemas['nullableValueRoot']
    assert.equal(validateConfiguration(value, null).valid, true)
    assert.equal(validateConfiguration(value, 12).valid, true)
    assert.equal(validateConfiguration(value, 1.5).valid, false)
    assert.equal(getSchemaView(value).nullable, true)
  })
})
const registrationSchema = {
  $schema: draft4,
  type: 'object',
  properties: {
    name: { type: 'string', minLength: 1, default: 'not injected' },
    optional: { type: 'string' },
    requiredNullable: { type: ['null', 'string'] },
    optionalNullable: { type: ['string', 'null'] },
    mode: { enum: ['read', 'write'] },
    start: { type: 'string', format: 'date-time' },
    samples: { type: 'array', items: { $ref: '#/definitions/sample' } },
    labels: { type: 'object', additionalProperties: { type: ['string', 'null'] } },
  },
  required: ['name', 'requiredNullable'],
  additionalProperties: false,
  definitions: { sample: { type: 'number', minimum: 0, exclusiveMinimum: true } },
}

describe('numeric field sessions', () => {
  it('does not finalize untouched fields or repeated blurs', () => {
    const session = new SchemaNumberSession()
    assert.equal(session.finish(), null)
    assert.equal(session.finish(), null)
  })

  it('finalizes valid edits exactly once, even when the token returns to its original value', () => {
    const session = new SchemaNumberSession()
    session.edit('2')
    session.edit('1')
    assert.equal(session.finish(), '1')
    assert.equal(session.finish(), null)
    session.edit('1.00')
    assert.equal(session.finish(), '1.00')
    assert.equal(session.finish(), null)
  })

  it('preserves empty, incomplete and unsafe edited tokens on blur', () => {
    const session = new SchemaNumberSession()
    for (const text of ['', '-', '1.', '1e', '9007199254740993']) {
      session.edit(text)
      assert.equal(session.finish(), text)
      assert.equal(session.finish(), null)
    }
  })
})

describe('Draft 4 configuration validation', () => {
  it('supports NJsonSchema guid, uint64 and decimal formats without blocking absent optional fields', () => {
    const schema = { type: 'object', properties: {
      id: { type: 'string', format: 'guid' }, count: { type: 'integer', format: 'uint64' }, amount: { type: 'number', format: 'decimal' },
    } }
    assert.equal(validateConfiguration(schema, {}).valid, true)
    for (const id of ['00000000-0000-0000-0000-000000000000', '6F9619FF-8B86-D011-B42D-00C04FC964FF']) {
      assert.equal(validateConfiguration(schema, { id, count: Number.MAX_SAFE_INTEGER, amount: 0.1 }).valid, true)
    }
    for (const id of ['', 'not-a-guid', '6f9619ff8b86d011b42d00c04fc964ff']) assert.equal(validateConfiguration(schema, { id }).valid, false)
    assert.equal(validateConfiguration(schema, { count: 0 }).valid, true)
    for (const count of [-1, 1.5, 9007199254740992, '1']) assert.equal(validateConfiguration(schema, { count }).valid, false)
    for (const amount of [Infinity, NaN, 9007199254740992, '0.1']) assert.equal(validateConfiguration(schema, { amount }).valid, false)
    assert.equal(validateConfiguration({ type: 'number', format: 'decimal', maximum: 1, multipleOf: 0.1 }, 0.3).valid, true)
    assert.equal(validateConfiguration({ type: 'number', format: 'decimal', maximum: 1 }, 1.1).valid, false)
    assert.equal(validateConfiguration({ type: 'number', format: 'decimal' }, 1e-29).valid, true)
  })

  it('accepts .NET TimeOnly and unspecified DateTime strings, retaining offsets and seven-digit precision', () => {
    for (const time of ['00:00:00', '12:34:56', '23:59:59.1234567', '12:34:56Z', '12:34:56.1+02:30', '12:34:56-14:00']) {
      assert.equal(validateConfiguration({ type: 'string', format: 'time' }, time).valid, true, time)
      const dateTime = `2024-02-29T${time}`
      assert.equal(validateConfiguration({ type: 'string', format: 'date-time' }, dateTime).valid, true, dateTime)
      assert.equal(configurationText(dateTime), JSON.stringify(dateTime))
    }
    for (const time of ['', '12:34', '24:00:00', '12:60:00', '12:00:60', '12:34:56.12345678',
      '12:34:56+14:01', '12:34:56-15:00', '12:34:56+02:60', '12:34:56+0230', '12:34:56\n', '12:34:56junk']) {
      assert.equal(validateConfiguration({ type: 'string', format: 'time' }, time).valid, false, time)
      assert.equal(validateConfiguration({ type: 'string', format: 'date-time' }, `2024-02-29T${time}`).valid, false, time)
    }
    for (const date of ['0000-01-01', '2023-02-29', '1900-02-29', '2024-04-31', '2024-00-01', '2024-13-01', '2024-01-00']) {
      assert.equal(validateConfiguration({ type: 'string', format: 'date-time' }, `${date}T12:34:56`).valid, false, date)
    }
    for (const date of ['0001-01-01', '9999-12-31', '2000-02-29']) {
      assert.equal(validateConfiguration({ type: 'string', format: 'date-time' }, `${date}T12:34:56`).valid, true, date)
    }
    assert.equal(validateConfiguration({ type: 'string', format: 'date-time' }, '2024-02-29 12:34:56').valid, false)
  })

  it('enforces explicit numeric byte bounds while preserving string base64 format behavior', () => {
    const numeric = { type: 'integer', format: 'byte', minimum: 0, maximum: 255 }
    for (const value of [0, 255]) assert.equal(validateConfiguration(numeric, value).valid, true)
    for (const value of [-1, 256, 1.5, 'AA==']) assert.equal(validateConfiguration(numeric, value).valid, false)
    assert.equal(validateConfiguration({ type: 'string', format: 'byte' }, 'AA==').valid, true)
    assert.equal(validateConfiguration({ type: 'string', format: 'byte' }, '!').valid, false)
  })
  it('fails closed instead of applying OpenAPI nullable semantics to Draft 4', () => {
    for (const nullable of [true, false]) {
      const schema = { $schema: draft4, type: 'string', nullable }
      for (const value of [null, 'text']) {
        const result = validateConfiguration(schema, value)
        assert.equal(result.valid, false)
        assert.match(result.errors.join(' '), /OpenAPI nullable/)
      }
      assert.equal(getSchemaView(schema).nullable, false)
      assert.equal(getSchemaView(schema).kind, 'raw')
      const nested = { type: 'object', properties: { optional: schema } }
      assert.equal(validateConfiguration(nested, {}).valid, false)
      assert.equal(getSchemaView(nested, ['#/properties/optional']).nullable, false)
    }
    assert.equal(validateConfiguration({ type: ['string', 'null'] }, null).valid, true)
    assert.equal(getSchemaView({ type: ['string', 'null'] }).nullable, true)
    assert.equal(validateConfiguration({ type: 'object', default: { nullable: true } }, {}).valid, true)
  })

  it('checks multipleOf with exact round-trip decimals, without epsilon tolerance', () => {
    for (const [multipleOf, valid, invalid] of [
      [0.1, [0, 0.3, -0.3, 1.2], [0.30000000000000004, 0.29999999999999993, -0.30000000000000004]],
      [1e-7, [3e-7, -3e-7, 1], [3.0000000000000004e-7, 1.5e-7]],
      [2, [0, -6, 100], [3, -3, 2.0000000000000004]],
      [2.5, [5, -7.5], [2.5000000000000004, 1]],
      [1e20, [0], [1e-20, 42]],
      [5e-324, [1e-323, -1e-323], [2.2250738585072014e-308]],
    ] as const) {
      const schema = { $schema: draft4, type: 'number', multipleOf }
      for (const value of valid) assert.equal(validateConfiguration(schema, value).valid, true, `${value} / ${multipleOf}`)
      for (const value of invalid) assert.equal(validateConfiguration(schema, value).valid, false, `${value} / ${multipleOf}`)
    }
    for (const multipleOf of [0, -1, Infinity]) {
      assert.equal(validateConfiguration({ type: 'number', multipleOf }, 0).valid, false)
    }
    const schema = { type: 'array', items: { type: 'number', multipleOf: 0.1 } }
    assert.equal(validateConfiguration(schema, [0.3, -0.3]).valid, true)
    const invalid = validateConfiguration(schema, [0.30000000000000004])
    assert.equal(invalid.valid, false)
    assert.match(invalid.errors.join(' '), /\/0.*multipleOf/)
    assert.equal(getSchemaView({ enum: [0.3, 0.30000000000000004], multipleOf: 0.1 }).enumValues.length, 1)
  })
  it('validates the original schema without coercion, defaults or removal', () => {
    const value = { requiredNullable: null, samples: ['2'], unknown: 1 }
    const snapshot = structuredClone(value)
    const schemaSnapshot = structuredClone(registrationSchema)
    const result = validateConfiguration(registrationSchema, value)
    assert.equal(result.valid, false)
    assert.ok(result.errors.some(error => error.includes('name')))
    assert.ok(result.errors.some(error => error.includes('unknown')))
    assert.ok(result.errors.some(error => error.includes('/samples/0')))
    assert.deepEqual(value, snapshot)
    assert.deepEqual(registrationSchema, schemaSnapshot)
    assert.equal(validateConfiguration(registrationSchema, { name: 'source', requiredNullable: null, samples: [1] }).valid, true)
    assert.equal(validateConfiguration(registrationSchema, { name: 'source', requiredNullable: null, samples: [0] }).valid, false)
  })

  it('distinguishes all four required/nullable combinations', () => {
    for (const required of [false, true]) for (const nullable of [false, true]) {
      const schema = { $schema: draft4, type: 'object', properties: { setting: { type: nullable ? ['null', 'string'] : 'string' } }, required: required ? ['setting'] : undefined }
      assert.equal(validateConfiguration(schema, {}).valid, !required)
      assert.equal(validateConfiguration(schema, { setting: null }).valid, nullable)
      assert.equal(validateConfiguration(schema, { setting: 'value' }).valid, true)
      const view = getSchemaView(schema)
      const property = view.properties[0]
      assert.equal(property.required, required)
      assert.equal(getSchemaView(schema, property.paths).nullable, nullable)
    }
  })

  it('requires a present JSON root, including for empty schemas', () => {
    assert.equal(validateConfiguration({}, undefined).valid, false)
    for (const value of [null, {}, [], false, 0, '']) assert.equal(validateConfiguration({}, value).valid, true)
    for (const value of [NaN, Infinity, -0, 9007199254740992, 1n, new Date(), { x: undefined }, [undefined]]) {
      assert.equal(validateConfiguration({}, value).valid, false)
    }
    const circular: Record<string, unknown> = {}
    circular['self'] = circular
    assert.equal(validateConfiguration({}, circular).valid, false)
  })

  it('fails closed for absent/malformed schemas and unresolved references, repeatedly', () => {
    for (const schema of [undefined, null, true, [], 'schema', { type: 'bogus' },
      { $ref: '#/definitions/missing' }, { $ref: 'https://example.invalid/schema.json' },
      { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'string' }]) {
      for (let i = 0; i < 2; i++) {
        const result = validateConfiguration(schema, {})
        assert.equal(result.valid, false)
        assert.ok(result.errors.length)
      }
      assert.equal(getSchemaView(schema).kind, 'raw')
    }
  })

  it('caches by schema identity without mixing roots with identical ids or retaining stale errors', () => {
    const schema = { id: 'urn:test:root', type: 'string', minLength: 2 }
    const other = { id: 'urn:test:root', type: 'number' }
    assert.equal(validateConfiguration(schema, 'a').valid, false)
    assert.equal(validateConfiguration(other, 1).valid, true)
    assert.deepEqual(validateConfiguration(schema, 'abc'), { valid: true, errors: [] })
    assert.equal(validateConfiguration(other, 'abc').valid, false)
  })

  it('keeps dates as strings and validates formats', () => {
    const schema = { type: 'string', format: 'date-time' }
    const value = '2026-09-16T12:30:00+02:00'
    assert.equal(validateConfiguration(schema, value).valid, true)
    assert.equal(getSchemaView(schema).kind, 'string')
    assert.equal(validateConfiguration(schema, 'yesterday').valid, false)
    assert.equal(validateConfiguration(schema, new Date()).valid, false)
  })

  it('ignores ref siblings as required by Draft 4, without rewriting the schema', () => {
    const schema = { $ref: '#/definitions/value', minLength: 100, definitions: { value: { type: 'string' } } }
    assert.equal(validateConfiguration(schema, 'text').valid, true)
    assert.equal(validateConfiguration(schema, 1).valid, false)
    assert.equal(getSchemaView(schema).kind, 'string')
  })

  it('fails closed for Ajv ref/type sibling limitations rather than using incorrect semantics', () => {
    const schema = { $ref: '#/definitions/value', type: 'number', definitions: { value: { type: 'string' } } }
    const result = validateConfiguration(schema, 'text')
    assert.equal(result.valid, false)
    assert.match(result.errors.join(' '), /sibling type/)
    assert.equal(getSchemaView(schema).kind, 'raw')
  })

  it('applies enum, array and unknown-field constraints', () => {
    assert.equal(validateConfiguration({ enum: [null, 'a', 2] }, null).valid, true)
    assert.equal(validateConfiguration({ enum: [null, 'a', 2] }, 'b').valid, false)
    const schema = { type: 'array', minItems: 1, uniqueItems: true, items: { type: 'integer' } }
    for (const value of [[], [1, 1], [1.5]]) assert.equal(validateConfiguration(schema, value).valid, false)
    assert.equal(validateConfiguration(schema, [1, 2]).valid, true)
    assert.equal(validateConfiguration({ type: 'object', additionalProperties: false }, { extra: 1 }).valid, false)
    assert.equal(validateConfiguration({ type: 'object' }, { extra: 1 }).valid, true)
  })

  it('fails closed for unknown formats even in optional properties and unused definitions', () => {
    for (const schema of [
      { type: 'string', format: 'unknown-extension-format' },
      { type: 'object', properties: { optional: { format: 'unknown-extension-format' } } },
      { type: 'object', definitions: { unused: { format: 'unknown-extension-format' } } },
      { type: 'object', properties: { x: { format: '__proto__' } } },
    ]) {
      const result = validateConfiguration(schema, {})
      assert.equal(result.valid, false)
      assert.match(result.errors.join(' '), /Unsupported format/)
      assert.equal(getSchemaView(schema).kind, 'raw')
    }
    assert.equal(validateConfiguration({ type: 'object', default: { format: 'not a schema' } }, {}).valid, true)
    assert.equal(validateConfiguration({ $ref: '#/definitions/value', format: 'ignored-sibling', definitions: { value: { type: 'string' } } }, 'ok').valid, true)
  })

  it('validates NJsonSchema TimeSpan formats with exact signed tick limits', () => {
    for (const format of ['time-span', 'duration']) {
      const schema = { type: ['string', 'null'], format }
      for (const value of ['00:00:00', '01:02:03', '1.02:03:04.0000001', '-00:00:00.0000001',
        '10675199.02:48:05.4775807', '-10675199.02:48:05.4775808']) {
        assert.equal(validateConfiguration(schema, value).valid, true, `${format}: ${value}`)
      }
      for (const value of ['', 'tomorrow', '24:00:00', '00:60:00', '00:00:60', '00:00:00.12345678',
        '10675199.02:48:05.4775808', '-10675199.02:48:05.4775809', '1:2:3', '00:00:01,5', '00:00:01\n']) {
        assert.equal(validateConfiguration(schema, value).valid, false, `${format}: ${value}`)
      }
      assert.equal(validateConfiguration(schema, null).valid, true)
      assert.equal(getSchemaView(schema).kind, 'string')
    }
    for (const value of ['P1D', 'PT1H', 'P1W']) {
      assert.equal(validateConfiguration({ type: 'string', format: 'duration' }, value).valid, true)
      assert.equal(validateConfiguration({ type: 'string', format: 'time-span' }, value).valid, false)
    }
    for (const value of ['P', 'PT', 'PT0.5S', '-PT1S']) {
      assert.equal(validateConfiguration({ type: 'string', format: 'duration' }, value).valid, false)
    }
  })

  it('distinguishes checked numeric formats from known annotation-only formats', () => {
    assert.equal(validateConfiguration({ type: 'integer', format: 'int32' }, 2147483647).valid, true)
    assert.equal(validateConfiguration({ type: 'integer', format: 'int32' }, 2147483648).valid, false)
    const int64 = { type: 'integer', format: 'int64', minimum: -9223372036854775808, maximum: 9223372036854775807 }
    assert.equal(validateConfiguration(int64, Number.MAX_SAFE_INTEGER).valid, true)
    for (const value of [9007199254740992, 1.5, '1']) assert.equal(validateConfiguration(int64, value).valid, false)
    for (const format of ['float', 'double']) {
      assert.equal(validateConfiguration({ type: 'number', format }, 0.1).valid, true)
      assert.equal(validateConfiguration({ type: 'number', format, maximum: 1 }, 2).valid, false)
    }
    for (const format of ['password', 'binary']) {
      assert.equal(validateConfiguration({ type: 'string', format }, 'unchecked payload').valid, true)
      assert.equal(validateConfiguration({ type: 'string', format, minLength: 1 }, '').valid, false)
    }
  })
})

describe('safe JSON parsing', () => {
  it('accepts ordinary decimals, exponent notation, strings and JSON roots', () => {
    for (const text of ['0', '1.0', '-2.5', '1e3', '0.1', '1e-7', '123.4500', '9007199254740991',
      '"9007199254740993"', '"escaped \\\" 9007199254740993"', 'null', 'false', '[]', '{"a":1.2}']) {
      const parsed = parseJsonSafely(text)
      assert.equal(parsed.valid, true, text)
      if (parsed.valid) assert.deepEqual(parsed.value, JSON.parse(text), text)
    }
  })

  it('rejects unsafe integer and decimal tokens before rounding, including exponent forms', () => {
    for (const text of ['9007199254740993', '9007199254740992', '-9007199254740993', '9.007199254740993e15',
      '9007199254740993.0', '1e309', '1e-400', '0.10000000000000001', '1.0000000000000001',
      '1.234567890123456789', '-0', '-0.0e100', '{"nested":[9223372036854775807]}']) {
      const parsed = parseJsonSafely(text)
      assert.equal(parsed.valid, false, text)
      assert.match(parsed.errors.join(' '), /precision loss/, text)
    }
  })

  it('rejects malformed/incomplete JSON without discarding its input', () => {
    for (const text of ['', '{', '{"n":1e}', '01', 'NaN', 'Infinity', '[1,]', '"unterminated']) {
      const parsed = parseJsonSafely(text)
      assert.equal(parsed.valid, false, text)
      assert.ok(parsed.errors.length)
    }
  })

  it('protects incoming pipeline response text before transport parsing, not schema metadata', () => {
    const response = '{"pipeline":{"registrations":[{"configuration":{"limit":9223372036854775807}}]}}'
    assert.equal(parseJsonSafely(response).valid, false)
    const safe = response.replace('9223372036854775807', '42')
    const parsed = parseJsonSafely(safe)
    assert.equal(parsed.valid, true)
    if (parsed.valid) assert.deepEqual(parsed.value, JSON.parse(safe))
    const description = '{"type":"integer","format":"int64","maximum":9223372036854775807}'
    assert.equal(parseJsonSafely(description).valid, false)
    assert.equal(validateConfiguration(JSON.parse(description), 42).valid, true)
  })
})

describe('conservative schema form projection', () => {
  it('uses aligned enum display names without changing values or weakening enum validation', () => {
    const schema = { type: ['integer', 'null'], enum: [null, 0, 1, 2], 'x-enumNames': ['Null', 'None', 'Read', 'Write'],
      'x-enumDisplayNames': ['Null label', 'No access', '', 'Write access'], not: { enum: [1] } }
    const view = getSchemaView(schema)
    assert.deepEqual(view.enumValues, [0, 2])
    assert.deepEqual(view.enumLabels, ['No access', 'Write access'])
    assert.equal(validateConfiguration(schema, 3).valid, false)
    assert.equal(validateConfiguration(schema, 'No access').valid, false)
    const names = { enum: [0, 1], 'x-enumNames': ['None', 'Read'], 'x-enumDisplayNames': ['Mismatched'] }
    assert.deepEqual(getSchemaView(names).enumLabels, ['None', 'Read'])
    assert.deepEqual(getSchemaView({ enum: [0, 1], 'x-enumNames': ['Mismatched'] }).enumLabels, ['0', '1'])
    assert.deepEqual(getSchemaView({ enum: [0, 1], 'x-enumNames': ['None', 'Read'], 'x-enumDisplayNames': ['', null] }).enumLabels, ['None', 'Read'])
    const flags = { type: 'integer', 'x-enumFlags': true }
    assert.equal(getSchemaView(flags).kind, 'integer')
    assert.equal(validateConfiguration(flags, 3).valid, true)
    assert.equal(validateConfiguration({ ...flags, enum: [0, 1, 2] }, 3).valid, false)
  })
  it('unwraps single-branch NJsonSchema ref wrappers and retains wrapper constraints', () => {
    for (const union of ['oneOf', 'anyOf']) {
      const schema = { type: 'object', properties: {
        setting: { title: 'Setting', [union]: [{ $ref: '#/definitions/value' }], enum: ['allowed'] },
      }, definitions: { value: { type: ['null', 'string'], default: 'not injected' } } }
      const snapshot = structuredClone(schema)
      const view = getSchemaView(schema, getSchemaView(schema).properties[0].paths)
      assert.equal(view.kind, 'enum')
      assert.deepEqual(view.enumValues, ['allowed'])
      assert.equal(view.nullable, false)
      assert.equal(validateConfiguration(schema, { setting: null }).valid, false)
      assert.equal(validateConfiguration(schema, { setting: 'allowed' }).valid, true)
      assert.deepEqual(schema, snapshot)
      const root = { [union]: [{ $ref: '#/definitions/value' }], definitions: { value: { type: 'object', properties: { count: { type: 'integer' } } } } }
      assert.equal(getSchemaView(root).kind, 'object')
      assert.equal(getSchemaView(root).properties[0].key, 'count')
    }
  })
  it('resolves root/local refs, escaped pointer keys and recursive object fields lazily', () => {
    const schema = { $schema: draft4, id: 'urn:root:ref', $ref: '#/definitions/root', definitions: {
      root: { type: 'object', properties: { next: { $ref: '#/definitions/root' }, name: { $ref: '#/definitions/a~1b~0c' } } },
      'a/b~c': { type: ['null', 'string'] },
    } }
    assert.equal(getSchemaView(schema).kind, 'object')
    const properties = getSchemaView(schema).properties
    assert.equal(getSchemaView(schema, properties[0].paths).kind, 'object')
    assert.equal(getSchemaView(schema, properties[1].paths).kind, 'string')
    assert.equal(getSchemaView(schema, properties[1].paths).nullable, true)
    assert.equal(validateConfiguration(schema, { name: null, next: { name: 'nested' } }).valid, true)
    assert.equal(schemaPointer('#', 'a/b~c'), '#/a~1b~0c')
  })

  it('supports nullable union ordering, while null must satisfy the complete schema', () => {
    for (const union of ['anyOf', 'oneOf']) for (const reverse of [false, true]) {
      const branches = [{ type: 'null' }, { type: 'string', minLength: 1 }]
      const schema = { [union]: reverse ? branches.reverse() : branches }
      assert.equal(getSchemaView(schema).kind, 'string')
      assert.equal(getSchemaView(schema).nullable, true)
      assert.equal(validateConfiguration(schema, '').valid, false)
    }
    for (const schema of [
      { type: ['null', 'string'], enum: ['a'] },
      { allOf: [{ type: ['null', 'string'] }, { not: { type: 'null' } }] },
      { anyOf: [{ type: 'null' }, { type: 'string' }], enum: ['a'] },
    ]) assert.equal(getSchemaView(schema).nullable, false)
  })

  it('combines common allOf properties, requirements and constraints without modifying schemas', () => {
    const schema = { allOf: [
      { type: 'object', properties: { a: { type: ['string', 'null'] } }, required: ['a'] },
      { type: 'object', properties: { b: { type: 'integer' }, a: { enum: ['yes'] } } },
    ] }
    const snapshot = structuredClone(schema)
    const view = getSchemaView(schema)
    assert.equal(view.kind, 'object')
    assert.deepEqual(view.properties.map(property => [property.key, property.required]), [['a', true], ['b', false]])
    assert.equal(getSchemaView(schema, view.properties[0].paths).nullable, false)
    assert.deepEqual(getSchemaView(schema, view.properties[0].paths).enumValues, ['yes'])
    assert.equal(validateConfiguration(schema, { a: 'yes', b: 1 }).valid, true)
    assert.equal(validateConfiguration(schema, { a: null }).valid, false)
    assert.deepEqual(schema, snapshot)
    for (const types of [['number', 'integer'], ['integer', 'number']]) {
      assert.equal(getSchemaView({ allOf: types.map(type => ({ type })) }).kind, 'integer')
    }
  })

  it('includes additionalProperties constraints from other allOf branches', () => {
    const schema = { allOf: [
      { type: 'object', properties: { name: { type: ['null', 'string'] } } },
      { additionalProperties: { type: 'string' } },
    ] }
    const view = getSchemaView(schema)
    assert.equal(getSchemaView(schema, view.properties[0].paths).nullable, false)
    assert.equal(getSchemaView(schema, view.additionalPaths).kind, 'string')
    assert.equal(getSchemaView({ allOf: [schema['allOf'][0], { additionalProperties: false }] }).kind, 'raw')
  })

  it('projects enums, arrays and dictionaries and creates values only explicitly, never defaults', () => {
    assert.equal(createSchemaValue(getSchemaView({ type: 'string', default: 'ignored' })), '')
    assert.deepEqual(createSchemaValue(getSchemaView(registrationSchema)), {})
    const view = getSchemaView(registrationSchema)
    const samples = getSchemaView(registrationSchema, view.properties.find(property => property.key === 'samples')!.paths)
    assert.equal(samples.kind, 'array')
    assert.equal(getSchemaView(registrationSchema, samples.itemPaths).kind, 'number')
    const labels = getSchemaView(registrationSchema, view.properties.find(property => property.key === 'labels')!.paths)
    assert.equal(labels.allowAdditional, true)
    assert.equal(getSchemaView(registrationSchema, labels.additionalPaths).nullable, true)
    const enumeration = getSchemaView({ type: ['null', 'integer'], enum: [null, 1, 2] })
    assert.equal(enumeration.kind, 'enum')
    assert.deepEqual(enumeration.enumValues, [1, 2])
    assert.equal(enumeration.nullable, true)
  })

  it('falls back for complex unions, tuples, pattern dictionaries and nested reference scopes', () => {
    for (const schema of [
      { oneOf: [{ type: 'string' }, { type: 'number' }] },
      { type: ['string', 'number'] },
      { type: 'array', items: [{ type: 'string' }, { type: 'integer' }] },
      { type: 'object', patternProperties: { '^x': { type: 'integer' } } },
      { allOf: [{ id: 'nested', type: 'string' }] },
    ]) assert.equal(getSchemaView(schema).kind, 'raw')
  })
})

describe('immutable configuration edits and drafts', () => {
  it('preserves incomplete decimal typing through recursive raw envelopes until repaired', () => {
    const snapshot = { items: [{ number: 1, unknown: 'retained' }] }
    for (const token of ['1', '1.', '1.2', '1.2e', '1.2e-2', '']) {
      const item = configurationWithRawMember(snapshot.items[0], 'number', token)
      const items = configurationWithRawMember(snapshot.items, 0, item)
      const draft = configurationWithRawMember(snapshot, 'items', items)
      const parsed = parseJsonSafely(draft)
      assert.equal(parsed.valid, ['1', '1.2', '1.2e-2'].includes(token), token)
      assert.ok(draft.includes(token))
      if (parsed.valid) assert.deepEqual(parsed.value, { items: [{ number: Number(token), unknown: 'retained' }] })
      assert.deepEqual(snapshot, { items: [{ number: 1, unknown: 'retained' }] })
    }
  })
  it('requires reset confirmation for every existing root value or raw buffer, including empty drafts', () => {
    assert.equal(configurationResetNeedsConfirmation(undefined, undefined), false)
    for (const value of [null, '', false, 0, {}, [], { populated: true }]) {
      assert.equal(configurationResetNeedsConfirmation(value, undefined), true)
    }
    for (const text of ['', ' ', '{', 'null', '{"unsafe":9007199254740993}']) {
      assert.equal(configurationResetNeedsConfirmation(undefined, text), true)
    }
  })

  it('does not reinterpret an invalid single field draft as array deletion/insertion or object keys', () => {
    for (const [value, key, token] of [
      [[1], 0, ''], [[1], 0, '1,2'], [[1], 0, '1],"injected":[2'], [{ x: 1 }, 'x', '1,"y":2'],
    ] as const) {
      const draft = configurationWithRawMember(structuredClone(value) as unknown[] | Record<string, unknown>, key, token)
      assert.equal(parseJsonSafely(draft).valid, false, draft)
      assert.ok(draft.includes(token))
      const nested = configurationWithRawMember({ items: value }, 'items', draft)
      assert.equal(parseJsonSafely(nested).valid, false, nested)
    }
  })

  it('distinguishes cleared strings, cleared numbers, explicit null and absent properties', () => {
    const initial = { field: 'before', unknown: 3 }
    assert.deepEqual(setConfigurationProperty(initial, 'field', ''), { field: '', unknown: 3 })
    assert.deepEqual(setConfigurationProperty(initial, 'field', null), { field: null, unknown: 3 })
    assert.deepEqual(setConfigurationProperty(initial, 'field', undefined, false), { unknown: 3 })
    for (const token of ['', '-', '1e', '9007199254740993']) {
      assert.equal(parseJsonSafely(configurationWithRawMember({ field: 1 }, 'field', token)).valid, false)
    }
    const nullable = getSchemaView({ type: ['string', 'null'], default: 'never injected' })
    assert.equal(nullable.kind, 'string')
    assert.equal(nullable.nullable, true)
    assert.equal(createSchemaValue(nullable), '')
  })
  it('preserves unknown fields and safely supports prototype-like and empty dictionary keys', () => {
    const parsed = parseJsonSafely('{"__proto__":{"polluted":true},"constructor":"a","prototype":1,"":null,"unknown":{"nested":2}}')
    assert.equal(parsed.valid, true)
    if (!parsed.valid) return
    const original = parsed.value as Record<string, unknown>
    const updated = setConfigurationProperty(original, '__proto__', { changed: true })
    assert.equal(Object.getPrototypeOf(updated), Object.prototype)
    assert.equal(Object.hasOwn(updated, '__proto__'), true)
    assert.equal(Object.hasOwn(Object.prototype, 'polluted'), false)
    assert.deepEqual(updated['unknown'], { nested: 2 })
    assert.deepEqual(original['__proto__'], { polluted: true })
    assert.equal(Object.hasOwn(setConfigurationProperty(updated, 'constructor', undefined, false), 'constructor'), false)
    assert.equal(Object.hasOwn(setConfigurationProperty(updated, '', false), ''), true)
    assert.equal(validateConfiguration({ type: 'object' }, updated).valid, true)
  })

  it('embeds invalid nested drafts without precision loss or altering adjacent values', () => {
    const object = { known: 1, unknown: { x: true } }
    const draft = configurationWithRawMember(object, 'known', '9007199254740993')
    assert.ok(draft.includes('9007199254740993'))
    assert.equal(parseJsonSafely(draft).valid, false)
    const nested = configurationWithRawMember({ items: [1, 2] }, 'items', configurationWithRawMember([1, 2], 1, '1e'))
    assert.equal(nested, '{"items":[1,1e]}')
    assert.deepEqual(object, { known: 1, unknown: { x: true } })
    assert.equal(configurationWithRawMember({}, '__proto__', 'null'), '{"__proto__":null}')
    assert.equal(configurationText(undefined), '')
    for (const value of [NaN, Infinity, -0, new Date(), { omitted: undefined }, 1n]) {
      assert.equal(configurationText(value), '')
    }
  })
})
